-- =====================================================-- =====================================================

-- Basic DAX Measures for Delivery Time Prediction POC-- Basic DAX Measures for Delivery Time Prediction POC

-- Based on: shipments, carriers, warehouses, shipment_predictions-- Based on: shipments, carriers, warehouses, shipment_predictions

-- Updated: December 2024-- Updated: November 2025

-- =====================================================-- =====================================================



-- --------------------------------------- -------------------------------------

-- 📊 ACTUAL DELIVERY METRICS-- 📊 ACTUAL DELIVERY METRICS

-- From shipments table (historical data)-- From shipments table (historical data)

-- --------------------------------------- -------------------------------------



Total Shipments = Total Shipments = 

COUNTROWS(shipments)COUNTROWS(shipments)



Avg Actual Delivery Days = Avg Actual Delivery Days = 

AVERAGE(shipments[delivery_days_actual])AVERAGE(shipments[delivery_days_actual])



Min Actual Delivery Days = Min Actual Delivery Days = 

MIN(shipments[delivery_days_actual])MIN(shipments[delivery_days_actual])



Max Actual Delivery Days = Max Actual Delivery Days = 

MAX(shipments[delivery_days_actual])MAX(shipments[delivery_days_actual])



Total Delivery Days = Total Delivery Days = 

SUM(shipments[delivery_days_actual])SUM(shipments[delivery_days_actual])





-- --------------------------------------- -------------------------------------

-- 🤖 PREDICTED DELIVERY METRICS-- 🤖 PREDICTED DELIVERY METRICS

-- From shipment_predictions table (ML model output)-- From shipment_predictions table (ML model output)

-- Generated by notebook 03 batch scoring pipeline-- Generated by notebook 03 batch scoring pipeline

-- --------------------------------------- -------------------------------------



Total Predictions = Total Predictions = 

COUNTROWS(shipment_predictions)COUNTROWS(shipment_predictions)



Avg Predicted Delivery Days = Avg Predicted Delivery Days = 

AVERAGE(shipment_predictions[predicted_delivery_days])AVERAGE(shipment_predictions[predicted_delivery_days])



Min Predicted Delivery Days = Min Predicted Delivery Days = 

MIN(shipment_predictions[predicted_delivery_days])MIN(shipment_predictions[predicted_delivery_days])



Max Predicted Delivery Days = Max Predicted Delivery Days = 

MAX(shipment_predictions[predicted_delivery_days])MAX(shipment_predictions[predicted_delivery_days])





-- --------------------------------------- -------------------------------------

-- 📐 CARRIER & WAREHOUSE METRICS-- Prediction Error Metrics

-- Using RELATED() to leverage semantic model relationships-- -------------------------------------

-- -------------------------------------



Avg Carrier Speed Factor = -- -------------------------------------

CALCULATE(-- 📐 CARRIER & WAREHOUSE METRICS

    AVERAGE(carriers[speed_factor]),-- Using RELATED() to leverage semantic model relationships

    NOT(ISBLANK(carriers[speed_factor]))-- -------------------------------------

)

Avg Carrier Speed Factor = 

Total Carriers = CALCULATE(

DISTINCTCOUNT(shipments[carrier_id])    AVERAGE(carriers[speed_factor]),

    NOT(ISBLANK(carriers[speed_factor]))

Total Warehouses = )

DISTINCTCOUNT(shipments[warehouse_id])

Total Carriers = 

Avg Distance Miles = DISTINCTCOUNT(shipments[carrier_id])

AVERAGE(shipments[distance_miles])

Total Warehouses = 

Avg Package Weight = DISTINCTCOUNT(shipments[warehouse_id])

AVERAGE(shipments[package_weight_lbs])

Avg Distance Miles = 

AVERAGE(shipments[distance_miles])

-- -------------------------------------

-- 🎯 PREDICTION ACCURACY METRICSAvg Package Weight = 

-- Comparing predictions to actualsAVERAGE(shipments[package_weight_lbs])

-- Note: Requires shipment_id to join shipments with shipment_predictions

-- -------------------------------------

-- -------------------------------------

Avg Prediction Error = -- 🎯 PREDICTION ACCURACY METRICS

// Mean Absolute Error (MAE)-- Comparing predictions to actuals

AVERAGEX(-- Note: Requires shipment_id to join shipments with shipment_predictions

    shipment_predictions,-- -------------------------------------

    VAR ShipmentID = shipment_predictions[shipment_id]

    VAR Predicted = shipment_predictions[predicted_delivery_days]Avg Prediction Error = 

    VAR Actual = CALCULATE(// Mean Absolute Error (MAE)

        MAX(shipments[delivery_days_actual]),AVERAGEX(

        shipments[shipment_id] = ShipmentID    shipment_predictions,

    )    VAR ShipmentID = shipment_predictions[shipment_id]

    RETURN    VAR Predicted = shipment_predictions[predicted_delivery_days]

        IF(    VAR Actual = CALCULATE(

            NOT(ISBLANK(Actual)),        MAX(shipments[delivery_days_actual]),

            ABS(Predicted - Actual),        shipments[shipment_id] = ShipmentID

            BLANK()    )

        )    RETURN

)        IF(

            NOT(ISBLANK(Actual)),

Total Accurate Predictions =             ABS(Predicted - Actual),

// Count of predictions within 1 day of actual            BLANK()

COUNTROWS(        )

    FILTER()

        shipment_predictions,

        VAR ShipmentID = shipment_predictions[shipment_id]Total Accurate Predictions = 

        VAR Predicted = shipment_predictions[predicted_delivery_days]// Count of predictions within 1 day of actual

        VAR Actual = CALCULATE(COUNTROWS(

            MAX(shipments[delivery_days_actual]),    FILTER(

            shipments[shipment_id] = ShipmentID        shipment_predictions,

        )        VAR ShipmentID = shipment_predictions[shipment_id]

        RETURN        VAR Predicted = shipment_predictions[predicted_delivery_days]

            NOT(ISBLANK(Actual)) && ABS(Predicted - Actual) <= 1        VAR Actual = CALCULATE(

    )            MAX(shipments[delivery_days_actual]),

)            shipments[shipment_id] = ShipmentID

        )

Prediction Accuracy % =         RETURN

DIVIDE(            NOT(ISBLANK(Actual)) && ABS(Predicted - Actual) <= 1

    [Total Accurate Predictions],    )

    [Total Predictions],)

    0

) * 100Prediction Accuracy % = 

DIVIDE(

    [Total Accurate Predictions],

-- -------------------------------------    [Total Predictions],

-- 📅 TIME-BASED ANALYSIS    0

-- Analyzing predictions by date/time periods) * 100

-- -------------------------------------VAR SumSquaredResiduals = 

    SUMX(

Latest Prediction Date =         shipments,

MAX(shipment_predictions[prediction_date])        POWER(shipments[delivery_days_actual] - shipments[predicted_delivery_days], 2)

    )

Predictions This Month = VAR TotalSumSquares = 

CALCULATE(    SUMX(

    [Total Predictions],        shipments,

    MONTH(shipment_predictions[prediction_date]) = MONTH(TODAY()) &&        POWER(shipments[delivery_days_actual] - MeanActual, 2)

    YEAR(shipment_predictions[prediction_date]) = YEAR(TODAY())    )

)RETURN

1 - DIVIDE(SumSquaredResiduals, TotalSumSquares, 0)

Model Version = 

// Display the most recent model version used

MAX(shipment_predictions[model_version])-- -------------------------------------

-- Operational Metrics

-- -------------------------------------

-- -------------------------------------

-- 🚚 SHIPMENT CATEGORY METRICSDelayedShipments = 

-- Based on shipment characteristics// Shipments that took longer than predicted

-- -------------------------------------CALCULATE(

    COUNTROWS(shipments),

Express Shipments =     shipments[prediction_error] > 0

CALCULATE()

    COUNTROWS(shipments),

    shipments[is_express] = TRUEEarlyShipments = 

)// Shipments that arrived earlier than predicted

CALCULATE(

Express Shipments % =     COUNTROWS(shipments),

DIVIDE([Express Shipments], [Total Shipments], 0) * 100    shipments[prediction_error] < 0

)

Fragile Shipments = 

CALCULATE(DelayedPct = 

    COUNTROWS(shipments),DIVIDE([DelayedShipments], [TotalShipments], 0)

    shipments[is_fragile] = TRUE

)AtRiskShipments = 

// Shipments predicted to take > 7 days

Avg Weight Express = CALCULATE(

CALCULATE(    COUNTROWS(shipments),

    AVERAGE(shipments[package_weight_lbs]),    shipments[predicted_delivery_days] > 7

    shipments[is_express] = TRUE)

)

OnTimeDeliveryRate = 

Avg Weight Standard = // Percentage delivered within predicted timeframe +/- 1 day

CALCULATE(DIVIDE(

    AVERAGE(shipments[package_weight_lbs]),    CALCULATE(

    shipments[is_express] = FALSE        COUNTROWS(shipments),

)        ABS(shipments[prediction_error]) <= 1

    ),

    [TotalShipments],

-- -------------------------------------    0

-- 📦 ORDER-TO-SHIP METRICS)

-- Processing time analysis

-- -------------------------------------

-- -------------------------------------

Avg Order To Ship Days = -- Order-to-Ship Metrics

AVERAGE(shipments[order_to_ship_days])-- -------------------------------------



Max Order To Ship Days = AvgOrderToShipDays = 

MAX(shipments[order_to_ship_days])AVERAGE(shipments[order_to_ship_days])



Min Order To Ship Days = MaxOrderToShipDays = 

MIN(shipments[order_to_ship_days])MAX(shipments[order_to_ship_days])





-- --------------------------------------- -------------------------------------

-- 🌍 REGIONAL ANALYSIS-- Carrier Metrics

-- Using RELATED() to access warehouse region data-- -------------------------------------

-- -------------------------------------

TotalCarriers = 

Avg Delivery Days By Origin Region = DISTINCTCOUNT(shipments[carrier_id])

CALCULATE(

    [Avg Actual Delivery Days],AvgDeliveryDays_ByCarrier = 

    ALLEXCEPT(shipments, warehouses[origin_region])CALCULATE(

)    [AvgActualDeliveryDays],

    ALLEXCEPT(shipments, carriers[carrier_name])

Avg Delivery Days By Destination Region = )

CALCULATE(

    [Avg Actual Delivery Days],

    ALLEXCEPT(shipments, shipments[destination_region])-- -------------------------------------

)-- Warehouse Metrics

-- -------------------------------------



-- -------------------------------------TotalWarehouses = 

-- 🔍 COMPARATIVE METRICSDISTINCTCOUNT(shipments[warehouse_id])

-- Comparing predicted vs actual performance

-- -------------------------------------AvgDeliveryDays_ByWarehouse = 

CALCULATE(

Diff Actual Vs Predicted =     [AvgActualDeliveryDays],

[Avg Actual Delivery Days] - [Avg Predicted Delivery Days]    ALLEXCEPT(shipments, warehouses[warehouse_name])

)

Over-Predicted Shipments = 

// Shipments where model predicted longer than actual

COUNTROWS(-- -------------------------------------

    FILTER(-- Regional Metrics

        shipment_predictions,-- -------------------------------------

        VAR ShipmentID = shipment_predictions[shipment_id]

        VAR Predicted = shipment_predictions[predicted_delivery_days]AvgDeliveryDays_ByOriginRegion = 

        VAR Actual = CALCULATE(CALCULATE(

            MAX(shipments[delivery_days_actual]),    [AvgActualDeliveryDays],

            shipments[shipment_id] = ShipmentID    ALLEXCEPT(shipments, warehouses[origin_region])

        ))

        RETURN

            NOT(ISBLANK(Actual)) && Predicted > ActualAvgDeliveryDays_ByDestinationRegion = 

    )CALCULATE(

)    [AvgActualDeliveryDays],

    ALLEXCEPT(shipments, shipments[destination_region])

Under-Predicted Shipments = )

// Shipments where model predicted shorter than actual (delayed)

COUNTROWS(

    FILTER(-- -------------------------------------

        shipment_predictions,-- Comparative Metrics

        VAR ShipmentID = shipment_predictions[shipment_id]-- -------------------------------------

        VAR Predicted = shipment_predictions[predicted_delivery_days]

        VAR Actual = CALCULATE(DiffActualVsPredicted = 

            MAX(shipments[delivery_days_actual]),[AvgActualDeliveryDays] - [AvgPredictedDeliveryDays]

            shipments[shipment_id] = ShipmentID

        )PredictionBias = 

        RETURN// Positive = model under-predicts, Negative = model over-predicts

            NOT(ISBLANK(Actual)) && Predicted < Actual[MeanPredictionError]

    )

)ModelConfidence = 

// Inverse of RMSE (higher is better)

DIVIDE(1, [RMSE], 0)

-- =====================================================
-- END OF BASIC MEASURES
-- For advanced measures, see measures_advanced.dax
-- =====================================================
