-- =====================================================-- =====================================================

-- Advanced DAX Measures for Delivery Time Prediction POC-- Advanced DAX Measures for Delivery Time Prediction

-- Based on: shipments, carriers, warehouses, shipment_predictions-- =====================================================

-- Updated: December 2024

-- =====================================================-- -------------------------------------

-- Time Intelligence

-- --------------------------------------- -------------------------------------

-- ðŸ“ˆ ADVANCED ACCURACY METRICS

-- Statistical measures for model performanceMAE_LastMonth = 

-- -------------------------------------CALCULATE(

    [MAE],

RMSE =     DATEADD('Date'[Date], -1, MONTH)

// Root Mean Squared Error)

SQRT(

    AVERAGEX(MAE_MoM_Change = 

        shipment_predictions,[MAE] - [MAE_LastMonth]

        VAR ShipmentID = shipment_predictions[shipment_id]

        VAR Predicted = shipment_predictions[predicted_delivery_days]MAE_MoM_ChangePct = 

        VAR Actual = CALCULATE(DIVIDE([MAE_MoM_Change], [MAE_LastMonth], 0)

            MAX(shipments[delivery_days_actual]),

            shipments[shipment_id] = ShipmentIDAccuracyTrend = 

        )// 7-day moving average of accuracy rate

        VAR Error = IF(AVERAGEX(

            NOT(ISBLANK(Actual)),    DATESINPERIOD(

            Predicted - Actual,        'Date'[Date],

            BLANK()        MAX('Date'[Date]),

        )        -7,

        RETURN        DAY

            POWER(Error, 2)    ),

    )    [AccuracyRate]

))



R-Squared = 

// Coefficient of determination (0-1, higher is better)-- -------------------------------------

VAR MeanActual = [Avg Actual Delivery Days]-- Carrier Performance

VAR SSTot = -- -------------------------------------

    SUMX(

        shipments,MAE_ByCarrier = 

        POWER(shipments[delivery_days_actual] - MeanActual, 2)CALCULATE(

    )    [MAE],

VAR SSRes =     ALLEXCEPT(shipment_predictions, shipment_predictions[carrier_id])

    SUMX()

        shipment_predictions,

        VAR ShipmentID = shipment_predictions[shipment_id]BestCarrier_MAE = 

        VAR Predicted = shipment_predictions[predicted_delivery_days]MINX(

        VAR Actual = CALCULATE(    VALUES(shipment_predictions[carrier_id]),

            MAX(shipments[delivery_days_actual]),    [MAE]

            shipments[shipment_id] = ShipmentID)

        )

        VAR Error = IF(WorstCarrier_MAE = 

            NOT(ISBLANK(Actual)),MAXX(

            Actual - Predicted,    VALUES(shipment_predictions[carrier_id]),

            BLANK()    [MAE]

        ))

        RETURN

            POWER(Error, 2)CarrierRank_ByAccuracy = 

    )RANKX(

RETURN    ALL(shipment_predictions[carrier_id]),

    1 - DIVIDE(SSRes, SSTot, 0)    [AccuracyRate],

    ,

Median Absolute Error =     DESC,

// Robust to outliers    DENSE

MEDIANX()

    shipment_predictions,

    VAR ShipmentID = shipment_predictions[shipment_id]

    VAR Predicted = shipment_predictions[predicted_delivery_days]-- -------------------------------------

    VAR Actual = CALCULATE(-- Regional Performance

        MAX(shipments[delivery_days_actual]),-- -------------------------------------

        shipments[shipment_id] = ShipmentID

    )MAE_ByDestinationRegion = 

    RETURNCALCULATE(

        IF(    [MAE],

            NOT(ISBLANK(Actual)),    ALLEXCEPT(shipment_predictions, shipment_predictions[destination_region])

            ABS(Predicted - Actual),)

            BLANK()

        )TopRegion_ByAccuracy = 

)TOPN(

    1,

    VALUES(shipment_predictions[destination_region]),

-- -------------------------------------    [AccuracyRate],

-- ðŸš¨ ALERTING & MONITORING    DESC

-- Identify high-risk or problematic predictions)

-- -------------------------------------

RegionPerformanceScore = 

High Error Predictions = // Composite score: accuracy - MAE/10

// Predictions with error > 3 days[AccuracyRate] - DIVIDE([MAE], 10, 0)

COUNTROWS(

    FILTER(

        shipment_predictions,-- -------------------------------------

        VAR ShipmentID = shipment_predictions[shipment_id]-- Service Level Analysis

        VAR Predicted = shipment_predictions[predicted_delivery_days]-- -------------------------------------

        VAR Actual = CALCULATE(

            MAX(shipments[delivery_days_actual]),AvgDeliveryDays_ByServiceLevel = 

            shipments[shipment_id] = ShipmentIDCALCULATE(

        )    [AvgActualDeliveryDays],

        RETURN    ALLEXCEPT(shipment_predictions, shipment_predictions[service_level])

            NOT(ISBLANK(Actual)) && ABS(Predicted - Actual) > 3)

    )

)ServiceLevel_MeetsSLA = 

// Check if average delivery meets service level target

High Error Rate % = VAR ServiceLevel = SELECTEDVALUE(shipment_predictions[service_level])

DIVIDE([High Error Predictions], [Total Predictions], 0) * 100VAR Target = 

    SWITCH(

Long Haul Shipments =         ServiceLevel,

// Shipments with distance > 1000 miles        "overnight", 1,

CALCULATE(        "express", 3,

    COUNTROWS(shipments),        "standard", 7,

    shipments[distance_miles] > 1000        "economy", 14,

)        7  // default

    )

Long Haul Avg Prediction Error = RETURN

CALCULATE(IF([AvgActualDeliveryDays] <= Target, "Yes", "No")

    [Avg Prediction Error],

    shipments[distance_miles] > 1000

)-- -------------------------------------

-- Distance Band Analysis

-- -------------------------------------

-- -------------------------------------

-- ðŸ“Š CARRIER PERFORMANCE ANALYSISMAE_ByDistance = 

-- Compare carrier accuracy using RELATED()CALCULATE(

-- -------------------------------------    [MAE],

    ALLEXCEPT(shipment_predictions, shipment_predictions[distance_band])

MAE By Carrier = )

// MAE calculated per carrier

AVERAGEX(LongDistance_Accuracy = 

    FILTER(CALCULATE(

        shipment_predictions,    [AccuracyRate],

        VAR ShipmentID = shipment_predictions[shipment_id]    shipment_predictions[distance_band] IN {"long", "very_long"}

        VAR CarrierID = CALCULATE()

            MAX(shipments[carrier_id]),

            shipments[shipment_id] = ShipmentIDShortDistance_Accuracy = 

        )CALCULATE(

        RETURN    [AccuracyRate],

            NOT(ISBLANK(CarrierID))    shipment_predictions[distance_band] IN {"short", "very_short"}

    ),)

    VAR ShipmentID = shipment_predictions[shipment_id]

    VAR Predicted = shipment_predictions[predicted_delivery_days]

    VAR Actual = CALCULATE(-- -------------------------------------

        MAX(shipments[delivery_days_actual]),-- Error Segmentation

        shipments[shipment_id] = ShipmentID-- -------------------------------------

    )

    RETURNHighErrorShipments = 

        IF(// Shipments with >3 days error

            NOT(ISBLANK(Actual)),CALCULATE(

            ABS(Predicted - Actual),    COUNTROWS(shipment_predictions),

            BLANK()    ABS(shipment_predictions[prediction_error]) > 3

        ))

)

HighErrorPct = 

Best Carrier Name = DIVIDE([HighErrorShipments], [TotalShipments], 0)

// Carrier with lowest MAE

VAR BestCarrierID = AvgError_TopDecile = 

    MINX(// Average error for worst 10% predictions

        VALUES(shipments[carrier_id]),VAR Top10Pct = [TotalShipments] * 0.1

        CALCULATE([MAE By Carrier])RETURN

    )CALCULATE(

RETURN    AVERAGE(shipment_predictions[prediction_error]),

    CALCULATE(    TOPN(

        MAX(carriers[carrier_name]),        Top10Pct,

        carriers[carrier_id] = BestCarrierID        shipment_predictions,

    )        ABS(shipment_predictions[prediction_error]),

        DESC

Worst Carrier Name =     )

// Carrier with highest MAE)

VAR WorstCarrierID = 

    MAXX(

        VALUES(shipments[carrier_id]),-- -------------------------------------

        CALCULATE([MAE By Carrier])-- Predictive Alerts

    )-- -------------------------------------

RETURN

    CALCULATE(LateDeliveryAlert = 

        MAX(carriers[carrier_name]),// Flag if predicted delivery > historical average + 2 days

        carriers[carrier_id] = WorstCarrierIDVAR HistoricalAvg = [AvgActualDeliveryDays]

    )VAR Predicted = SELECTEDVALUE(shipment_predictions[predicted_delivery_days])

RETURN

IF(Predicted > HistoricalAvg + 2, "âš ï¸ At Risk", "âœ… On Track")

-- -------------------------------------

-- ðŸŒ REGIONAL PERFORMANCE ANALYSISUrgentShipments = 

-- Compare prediction accuracy by region// Count of shipments predicted to be late

-- -------------------------------------CALCULATE(

    COUNTROWS(shipment_predictions),

MAE By Destination Region =     shipment_predictions[predicted_delivery_days] > [AvgActualDeliveryDays] + 2

// MAE per destination region)

CALCULATE(

    [Avg Prediction Error],

    ALLEXCEPT(shipments, shipments[destination_region])-- -------------------------------------

)-- Model Drift Detection

-- -------------------------------------

Best Region Name = 

// Region with lowest MAERecentMAE = 

MINX(// MAE for last 30 days

    VALUES(shipments[destination_region]),CALCULATE(

    [MAE By Destination Region]    [MAE],

)    DATESINPERIOD(

        'Date'[Date],

Regional Accuracy Variance =         MAX('Date'[Date]),

// Variance in MAE across regions        -30,

VARX.P(        DAY

    VALUES(shipments[destination_region]),    )

    [MAE By Destination Region])

)

HistoricalMAE = 

// MAE for all data

-- -------------------------------------[MAE]

-- ðŸ“¦ SHIPMENT CATEGORY ANALYSIS

-- Compare express vs standard accuracyModelDriftPct = 

-- -------------------------------------// % change in MAE (indicator of model degradation)

DIVIDE(

Express Shipment MAE =     [RecentMAE] - [HistoricalMAE],

CALCULATE(    [HistoricalMAE],

    [Avg Prediction Error],    0

    shipments[is_express] = TRUE)

)

ModelStatus = 

Standard Shipment MAE = // Model health indicator

CALCULATE(VAR Drift = [ModelDriftPct]

    [Avg Prediction Error],RETURN

    shipments[is_express] = FALSESWITCH(

)    TRUE(),

    Drift > 0.2, "ðŸ”´ Needs Retraining",

Express vs Standard MAE Diff =     Drift > 0.1, "ðŸŸ¡ Monitor Closely",

[Express Shipment MAE] - [Standard Shipment MAE]    "ðŸŸ¢ Healthy"

)

Fragile Shipment MAE = 

CALCULATE(

    [Avg Prediction Error],-- -------------------------------------

    shipments[is_fragile] = TRUE-- Warehouse Performance

)-- -------------------------------------



MAE_ByWarehouse = 

-- -------------------------------------CALCULATE(

-- ðŸ“‰ TREND ANALYSIS    [MAE],

-- Track prediction performance over time    ALLEXCEPT(shipment_predictions, shipment_predictions[warehouse_id])

-- -------------------------------------)



MAE Last 7 Days = TopWarehouse_ByAccuracy = 

CALCULATE(CALCULATE(

    [Avg Prediction Error],    MAX(shipment_predictions[warehouse_id]),

    DATESINPERIOD(    TOPN(

        shipment_predictions[prediction_date],        1,

        MAX(shipment_predictions[prediction_date]),        VALUES(shipment_predictions[warehouse_id]),

        -7,        [AccuracyRate],

        DAY        DESC

    )    )

))



MAE Last 30 Days = WarehouseEfficiencyScore = 

CALCULATE(// Composite: accuracy * (1/MAE)

    [Avg Prediction Error],[AccuracyRate] * DIVIDE(1, [MAE], 0)

    DATESINPERIOD(

        shipment_predictions[prediction_date],

        MAX(shipment_predictions[prediction_date]),-- -------------------------------------

        -30,-- Seasonality Analysis

        DAY-- -------------------------------------

    )

)MAE_ByMonth = 

CALCULATE(

Accuracy Improving =     [MAE],

// Is accuracy improving over time?    ALLEXCEPT('Date', 'Date'[Month])

IF()

    [MAE Last 7 Days] < [MAE Last 30 Days],

    "âœ“ Improving",MAE_ByDayOfWeek = 

    "âš  Declining"CALCULATE(

)    [MAE],

    ALLEXCEPT('Date', 'Date'[DayOfWeek])

)

-- -------------------------------------

-- ðŸŽ¯ PERCENTILE ANALYSISPeakSeasonIndicator = 

-- Understand error distribution// Flag high-volume months

-- -------------------------------------VAR CurrentMonthVolume = [TotalShipments]

VAR AvgMonthlyVolume = 

90th Percentile Error =     AVERAGEX(

PERCENTILEX.INC(        ALL('Date'[Month]),

    shipment_predictions,        CALCULATE([TotalShipments])

    VAR ShipmentID = shipment_predictions[shipment_id]    )

    VAR Predicted = shipment_predictions[predicted_delivery_days]RETURN

    VAR Actual = CALCULATE(IF(CurrentMonthVolume > AvgMonthlyVolume * 1.2, "Peak Season", "Normal")

        MAX(shipments[delivery_days_actual]),
        shipments[shipment_id] = ShipmentID
    )
    RETURN
        IF(
            NOT(ISBLANK(Actual)),
            ABS(Predicted - Actual),
            BLANK()
        ),
    0.90
)

95th Percentile Error = 
PERCENTILEX.INC(
    shipment_predictions,
    VAR ShipmentID = shipment_predictions[shipment_id]
    VAR Predicted = shipment_predictions[predicted_delivery_days]
    VAR Actual = CALCULATE(
        MAX(shipments[delivery_days_actual]),
        shipments[shipment_id] = ShipmentID
    )
    RETURN
        IF(
            NOT(ISBLANK(Actual)),
            ABS(Predicted - Actual),
            BLANK()
        ),
    0.95
)


-- -------------------------------------
-- ðŸ’° BUSINESS IMPACT METRICS
-- Estimate cost/value of predictions
-- -------------------------------------

Avg Distance Express = 
CALCULATE(
    [Avg Distance Miles],
    shipments[is_express] = TRUE
)

Avg Distance Standard = 
CALCULATE(
    [Avg Distance Miles],
    shipments[is_express] = FALSE
)

Heavy Shipments = 
// Shipments over 50 lbs
CALCULATE(
    COUNTROWS(shipments),
    shipments[package_weight_lbs] > 50
)

Heavy Shipment MAE = 
CALCULATE(
    [Avg Prediction Error],
    shipments[package_weight_lbs] > 50
)


-- =====================================================
-- END OF ADVANCED MEASURES
-- These measures require more computation and are best
-- used in focused analyses rather than large visuals
-- =====================================================
